//! `cogent doctor` — collect diagnostic info and threshold health warnings.

use colored::Colorize;
use serde_json::json;
use std::collections::HashMap;

/// Gather diagnostic information: versions, config, PATH, available binaries, OS info.
pub fn collect_diagnostics() -> serde_json::Value {
    let mut binaries = HashMap::new();
    for bin in &[
        "cogent",
        "cargo",
        "rustc",
        "git",
        "clippy-driver",
    ] {
        binaries.insert(
            *bin,
            which(bin).unwrap_or_else(|| "not found".to_string()),
        );
    }

    let mut config = json!({});
    if let Ok(content) = std::fs::read_to_string(".quality.toml") {
        config = json!({ "present": true, "size_bytes": content.len() });
    } else {
        config = json!({ "present": false });
    }

    json!({
        "cogent_version": env!("CARGO_PKG_VERSION"),
        "rust_version": rustc_version(),
        "cargo_version": cargo_version(),
        "platform": std::env::consts::OS,
        "arch": std::env::consts::ARCH,
        "path": std::env::var("PATH").unwrap_or_default(),
        "cwd": std::env::current_dir()
            .map(|p| p.to_string_lossy().to_string())
            .unwrap_or_default(),
        "config": config,
        "binaries": binaries,
        "git_repo": git_repo_info(),
    })
}

/// Run the doctor command and print diagnostics to stdout.
pub fn doctor_command(format: &str) -> i32 {
    let diagnostics = collect_diagnostics();
    let warnings = check_threshold_health();
    match format {
        "json" => {
            let mut output = diagnostics.clone();
            if !warnings.is_empty() {
                output["threshold_warnings"] = serde_json::to_value(&warnings).unwrap_or_default();
            }
            println!("{}", serde_json::to_string_pretty(&output).unwrap_or_default());
        }
        _ => {
            // Pretty human-readable output
            println!("  {}", "Cogent Diagnostic Report".bold());
            println!();
            println!(
                "  {} Cogent version: {}",
                "•".cyan(),
                diagnostics["cogent_version"].as_str().unwrap_or("unknown")
            );
            println!(
                "  {} Rust version:     {}",
                "•".cyan(),
                diagnostics["rust_version"].as_str().unwrap_or("unknown")
            );
            println!(
                "  {} Platform:         {} ({})",
                "•".cyan(),
                diagnostics["platform"].as_str().unwrap_or("unknown"),
                diagnostics["arch"].as_str().unwrap_or("unknown")
            );
            println!();
            println!("  {}", "Available binaries:".bold());
            if let Some(map) = diagnostics["binaries"].as_object() {
                for (name, path) in map {
                    let path_str = path.as_str().unwrap_or("unknown");
                    let icon = if path_str == "not found" {
                        "✗".red()
                    } else {
                        "✓".green()
                    };
                    println!("    {} {:20} {}", icon, name, path_str.bright_black());
                }
            }
            println!();
            println!(
                "  {} Config (.quality.toml): {}",
                "•".cyan(),
                if diagnostics["config"]["present"].as_bool() == Some(true) {
                    "present".green().to_string()
                } else {
                    "missing".yellow().to_string()
                }
            );
            if let Some(repo) = diagnostics["git_repo"].as_str() {
                println!("  {} Git repo:           {}", "•".cyan(), repo);
            }
            // Threshold health warnings
            if !warnings.is_empty() {
                println!();
                println!("  {}", "Threshold Health:".bold());
                for w in &warnings {
                    println!("    {} {}", "⚠".yellow(), w.suggestion);
                }
            }
        }
    }
    0
}

/// Warning about a threshold that is too close to its actual value.
#[derive(Debug, Clone, serde::Serialize)]
pub struct ThresholdWarning {
    pub threshold_name: String,
    pub current_value: f64,
    pub margin_pct: f64,
    pub suggestion: String,
}

/// Load `.quality.toml` thresholds and compare against actual baseline values.
/// Returns warnings for any threshold within 5% of its current baseline.
///
/// Baselines are loaded from `.cogent-baselines.json` if present (generated by
/// `cogent check . --save-baselines`), otherwise hardcoded defaults from the
/// cogent codebase are used.
pub fn check_threshold_health() -> Vec<ThresholdWarning> {
    let baselines = load_baselines();
    let Ok(content) = std::fs::read_to_string(".quality.toml") else {
        return Vec::new();
    };
    let mut warnings = Vec::new();
    for &(key, baseline, label) in &baselines {
        if let Some(threshold) = cogent_common::parse_toml_f64_aware(&content, key) {
            if baseline <= 0.0 {
                continue;
            }
            let margin_pct = ((threshold - baseline) / baseline * 100.0).max(0.0);
            if margin_pct < 5.0 {
                let suggested = (baseline * 1.10).ceil() as usize;
                warnings.push(ThresholdWarning {
                    threshold_name: key.to_string(),
                    current_value: threshold,
                    margin_pct,
                    suggestion: format!(
                        "{}: threshold {:.0} is within {:.1}% of actual ({:.0}). Consider lowering to ~{}.",
                        label, threshold, margin_pct, baseline, suggested
                    ),
                });
            }
        }
    }
    warnings
}

/// Baseline entry: (toml_key, actual_value, human_label).
const DEFAULT_BASELINES: &[(&str, f64, &str)] = &[
    ("max_avg", 61.79, "crap avg score"),
    ("max_markers", 16.0, "debt markers"),
    ("max_violations", 188.0, "complexity violations"),
    ("max_duplicates", 18.0, "duplication groups"),
    ("max_secrets", 128.0, "secret findings"),
    ("max_errhandle", 768.0, "error handling findings"),
    ("max_linelen", 285.0, "line length violations"),
    ("max_fuzz_risk", 459.0, "fuzzable endpoints"),
    ("max_deadcode", 136.0, "dead code findings"),
    ("max_halstead_bugs", 878.0, "halstead estimated bugs"),
];

/// Load baselines from `.cogent-baselines.json` if present, otherwise
/// fall back to [`DEFAULT_BASELINES`].
fn load_baselines() -> Vec<(&'static str, f64, &'static str)> {
    if let Ok(content) = std::fs::read_to_string(".cogent-baselines.json") {
        if let Ok(map) = serde_json::from_str::<serde_json::Map<String, serde_json::Value>>(&content) {
            let mut result: Vec<(&str, f64, &str)> = DEFAULT_BASELINES
                .iter()
                .copied()
                .collect();
            // Override baseline values from JSON
            for &(key, _, label) in DEFAULT_BASELINES.iter() {
                if let Some(val) = map.get(key).and_then(|v| v.as_f64()) {
                    if let Some(entry) = result.iter_mut().find(|(k, _, _)| *k == key) {
                        entry.1 = val;
                    }
                    let _ = label; // keep default label
                }
            }
            return result;
        }
    }
    DEFAULT_BASELINES.to_vec()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_load_baselines_defaults_when_no_file() {
        // In a temp dir with no .cogent-baselines.json, should return defaults
        let original = std::env::current_dir().unwrap();
        let tmp = tempfile::tempdir().unwrap();
        let _ = std::env::set_current_dir(tmp.path());
        let baselines = load_baselines();
        let _ = std::env::set_current_dir(&original);

        assert_eq!(baselines.len(), DEFAULT_BASELINES.len());
        assert_eq!(baselines[0].0, "max_avg");
        assert_eq!(baselines[0].1, 61.79);
        assert_eq!(baselines[0].2, "crap avg score");
    }

    #[test]
    fn test_load_baselines_overrides_from_json() {
        let tmp = tempfile::tempdir().unwrap();
        let original = std::env::current_dir().unwrap();
        let _ = std::env::set_current_dir(tmp.path());

        // Write a baselines file that overrides max_secrets
        let json = serde_json::json!({
            "max_secrets": 50.0,
            "max_avg": 99.0
        });
        std::fs::write(".cogent-baselines.json", serde_json::to_string_pretty(&json).unwrap()).unwrap();

        let baselines = load_baselines();
        let _ = std::env::set_current_dir(&original);

        // Overridden values
        let secrets = baselines.iter().find(|(k, _, _)| *k == "max_secrets").unwrap();
        assert_eq!(secrets.1, 50.0, "max_secrets should be overridden to 50");

        let crap = baselines.iter().find(|(k, _, _)| *k == "max_avg").unwrap();
        assert_eq!(crap.1, 99.0, "max_avg should be overridden to 99");

        // Non-overridden values stay default
        let markers = baselines.iter().find(|(k, _, _)| *k == "max_markers").unwrap();
        assert_eq!(markers.1, 16.0, "max_markers should stay at default 16");
    }

    #[test]
    fn test_load_baselines_invalid_json_falls_back() {
        let tmp = tempfile::tempdir().unwrap();
        let original = std::env::current_dir().unwrap();
        let _ = std::env::set_current_dir(tmp.path());

        std::fs::write(".cogent-baselines.json", "not valid json").unwrap();
        let baselines = load_baselines();
        let _ = std::env::set_current_dir(&original);

        // Should fall back to defaults
        assert_eq!(baselines.len(), DEFAULT_BASELINES.len());
        assert_eq!(baselines[0].1, 61.79);
    }

    #[test]
    fn test_check_threshold_health_no_config_returns_empty() {
        let original = std::env::current_dir().unwrap();
        let tmp = tempfile::tempdir().unwrap();
        let _ = std::env::set_current_dir(tmp.path());
        let warnings = check_threshold_health();
        let _ = std::env::set_current_dir(&original);
        assert!(warnings.is_empty(), "no .quality.toml should mean no warnings");
    }

    #[test]
    fn test_threshold_warning_struct_serializes() {
        let w = ThresholdWarning {
            threshold_name: "max_secrets".into(),
            current_value: 135.0,
            margin_pct: 3.5,
            suggestion: "lower to 145".into(),
        };
        let json = serde_json::to_value(&w).unwrap();
        assert_eq!(json["threshold_name"], "max_secrets");
        assert_eq!(json["current_value"], 135.0);
    }
}

fn which(name: &str) -> Option<String> {
    std::env::var_os("PATH").and_then(|paths| {
        std::env::split_paths(&paths).find_map(|dir| {
            let full = dir.join(name);
            if full.is_file() {
                Some(full.to_string_lossy().to_string())
            } else {
                None
            }
        })
    })
}

fn rustc_version() -> String {
    std::process::Command::new("rustc")
        .arg("--version")
        .output()
        .ok()
        .and_then(|o| String::from_utf8(o.stdout).ok())
        .map(|s| s.trim().to_string())
        .unwrap_or_else(|| "unknown".to_string())
}

fn cargo_version() -> String {
    std::process::Command::new("cargo")
        .arg("--version")
        .output()
        .ok()
        .and_then(|o| String::from_utf8(o.stdout).ok())
        .map(|s| s.trim().to_string())
        .unwrap_or_else(|| "unknown".to_string())
}

fn git_repo_info() -> Option<String> {
    std::process::Command::new("git")
        .args(["remote", "get-url", "origin"])
        .output()
        .ok()
        .and_then(|o| {
            if o.status.success() {
                String::from_utf8(o.stdout).ok().map(|s| s.trim().to_string())
            } else {
                None
            }
        })
}
